CREATE DATABASE BTVN_01;

USE BTVN_01;
CREATE TABLE KHACH_HANG(
	MaKH VARCHAR(50) PRIMARY KEY,
	TenKH VARCHAR(200),
	DiaChi VARCHAR(200),
	SoDT INT 
);

CREATE TABLE PHONG(
	MaPhong VARCHAR(50) PRIMARY KEY,
	LoaiPhong VARCHAR(200),
	SoKhachToiDa INT,
	GiaPhong INT,
	MoTa VARCHAR(200)
);

CREATE TABLE DAT_PHONG(
	MaDatPhong VARCHAR(50) PRIMARY KEY,
	MaPhong VARCHAR(50),
	MaKH VARCHAR(50),
	NgayDat DATE,
	GioBatDau DATETIME,
	GioKetThuc DATETIME,
	TienDatCoc INT,
	GhiChu VARCHAR(200),
	TrangThaiDat VARCHAR(50),
	CONSTRAINT MaKH_foreign FOREIGN KEY (MaKH) REFERENCES KHACH_HANG (MaKH),
	CONSTRAINT MaPhong_foreign FOREIGN KEY (MaPhong) REFERENCES PHONG (MaPhong) 
);

CREATE TABLE DICH_VU_DI_KEM(
	MaDV VARCHAR(50) PRIMARY KEY,
	TenDV VARCHAR(200),
	DonViTinh VARCHAR(50),
	DonGia INT
);

CREATE TABLE CHI_TIET_SU_DUNG_DV(
	MaDatPhong VARCHAR(50),
	MaDV VARCHAR(50),
	SoLuong INT,
	PRIMARY KEY (MaDatPhong, MaDV),
	CONSTRAINT MaDatPhong_foreign FOREIGN KEY (MaDatPhong) REFERENCES DAT_PHONG (MaDatPhong),
	CONSTRAINT MaDV_foreign FOREIGN KEY (MaDV) REFERENCES DICH_VU_DI_KEM (MaDV)
);

USE BTVN_01;
ALTER TABLE `KHACH_HANG` MODIFY COLUMN SoDT VARCHAR(15);
ALTER TABLE `DAT_PHONG` MODIFY COLUMN GioBatDau TIME ;
ALTER TABLE `DAT_PHONG` MODIFY COLUMN GioKetThuc TIME ;

USE BTVN_01;
SELECT * 
FROM `CHI_TIET_SU_DUNG_DV`
WHERE SoLuong BETWEEN 3 AND 10;

USE BTVN_01;
UPDATE `PHONG`
SET GiaPhong = GiaPhong + 10000
WHERE SoKhachToiDa > 10;

DELETE `CHI_TIET_SU_DUNG_DV`, `DAT_PHONG`
FROM `DAT_PHONG`
INNER JOIN `CHI_TIET_SU_DUNG_DV`
ON `DAT_PHONG`.MaDatPhong = `CHI_TIET_SU_DUNG_DV`.MaDatPhong
WHERE `DAT_PHONG`.TrangThaiDat LIKE 'Da huy';

SELECT `KHACH_HANG`.TenKH
FROM `KHACH_HANG` 
WHERE (TenKH LIKE 'H%' OR TenKH LIKE 'N%' OR TenKH LIKE 'M%') AND CHAR_LENGTH(TenKH) <= 20;